#!/bin/sh

mkdir garbage-amp
mkdir garbage-amp/pieces

cp SPEAKER-MAINTENANCE ERRORS README tuning schematic.png components-list \
    garbage-amp
cp pcb.blend front.blend back.blend battery-holder.blend battery-door.blend \
    left.blend right.blend top.blend top.printfix.blend garbage-amp/pieces
cp combined/combined.blend garbage-amp/pieces-assembled.blend

# TODO: Add photos

tar -cf garbage-amp.tar garbage-amp
gzip -9 garbage-amp.tar

cat garbage-amp.tar.gz >/var/www/archive/garbage-amp.tar.gz
rm -r garbage-amp
rm garbage-amp.tar.gz
